### ISSUE TITLE
Sorry, I meant to remove the private method since we don't use `academyId` anymore in the production code.

### ISSUE THREAD

**Issue by LBHBomotoso** [LBHackney-IT/academy-resident-information-api#25]
Sorry, I meant to remove the private method since we don't use `academyId` anymore in the production code.

I think it would cause some tests to need updating. 
But you should be able to replace usages of `academyId` with `claimId` and `personRef`

_Originally posted by @Renny4Real in https://github.com/LBHackney-IT/academy-resident-information-api/pull/24_

**Comment by LBHBomotoso** [comment]
This would break all the list endpoint tests. This isn't used in any of the get by id tests.

**Comment by Renny4Real** [comment]
That makes sense. Maybe it could be done separately. 
Agree that if it doesn't affect view endpoint tests, then removing it shouldn't be part of this PR.

**Comment by Duslerke** [comment]
No longer relevant as the application is decommissioned.
